const users = [
    {first_name: 'James',
    last_name: 'Bond',
    password: 123,
    address: '201 Huntington Way, Boise, ID, 60597',
    isAdmin: true,
    email:'james@gmail.com',
    },
    {first_name: 'Mike',
    last_name: 'Ishikawa',
    password: 123,
    address: '205 Bear Way, Boise, ID, 60597',
    isAdmin: false,
    email:'mikeIshi@gmail.com',
    },
    {first_name: 'Jessica',
    last_name: 'Lynn',
    password: 123,
    address: '345 Oracle Lane, Atlanta, GA, 60597',
    isAdmin: false,
    email:'Jess@gmail.com',
    },
    {first_name: 'Andrew',
    last_name: 'Luck',
    password: 123,
    address: '576 Freedom Drive, Boise, ID, 60597',
    isAdmin: false,
    email:'aLuck@gmail.com',
    },
    {first_name: 'Michael',
    last_name: 'Jordan',
    password: 123,
    address: '569 Stone Drive, Coopertown, NY, 56732',
    isAdmin: true,
    email:'MJ@gmail.com',
    },
    {first_name: 'Josie',
    last_name: 'Wang',
    password: 123,
    address: '713 Fuji Lane, Pensacola, FL, 98065',
    isAdmin: false,
    email:'josie@gmail.com',
    },
    {first_name: 'Alex',
    last_name: 'Trebek',
    password: 123,
    address: '900 Fuji Lane, Treasure Island, FL, 98065',
    isAdmin: false,
    email:'Alex@gmail.com',
    },
    {first_name: 'Tina',
    last_name: 'Young',
    password: 123,
    address: '569 Stone Drive, Coopertown, NY, 56732',
    isAdmin: true,
    email:'M@gmail.com',
    },
    {first_name: 'Josie',
    last_name: 'Wang',
    password: 123,
    address: '713 Fuji Lane, Pensacola, FL, 98065',
    isAdmin: false,
    email:'josie@gmail.com',
    },
    {first_name: 'Sally',
    last_name: 'Jones',
    password: 123,
    address: '900 Fuji Lane, Treasure Island, FL, 98065',
    isAdmin: false,
    email:'Sally@gmail.com',
    },
]